//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\parser\JsonLT.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace JsonLT.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class JsonLTLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, TRUE=12, FALSE=13, NULL=14, STRING=15, NUMBER=16, WS=17, 
		ROOT=18, CURRENT=19, TAG=20, NODENAME=21, OPERATOR=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "TRUE", "FALSE", "NULL", "STRING", "ESC", "UNICODE", 
		"HEX", "SAFECODEPOINT", "NUMBER", "INT", "EXP", "WS", "ROOT", "CURRENT", 
		"TAG", "NODENAME", "OPERATOR"
	};


	public JsonLTLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JsonLTLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'['", "']'", "'.'", "'[''", "'']'", 
		"'[?('", "')]'", "'true'", "'false'", "'null'", null, null, null, "'$'", 
		"'@'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"TRUE", "FALSE", "NULL", "STRING", "NUMBER", "WS", "ROOT", "CURRENT", 
		"TAG", "NODENAME", "OPERATOR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JsonLT.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JsonLTLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xB5', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', 
		'j', '\n', '\x10', '\f', '\x10', '\xE', '\x10', 'm', '\v', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', 't', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x5', '\x15', '\x81', '\n', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x6', '\x15', '\x86', 
		'\n', '\x15', '\r', '\x15', '\xE', '\x15', '\x87', '\x5', '\x15', '\x8A', 
		'\n', '\x15', '\x3', '\x15', '\x5', '\x15', '\x8D', '\n', '\x15', '\x3', 
		'\x16', '\x6', '\x16', '\x90', '\n', '\x16', '\r', '\x16', '\xE', '\x16', 
		'\x91', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x96', '\n', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x6', '\x18', '\x9B', '\n', 
		'\x18', '\r', '\x18', '\xE', '\x18', '\x9C', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\xA8', '\n', '\x1B', '\f', 
		'\x1B', '\xE', '\x1B', '\xAB', '\v', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\a', '\x1C', '\xAF', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', '\xB2', 
		'\v', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x2', '\x2', '\x1E', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x2', '#', 
		'\x2', '%', '\x2', '\'', '\x2', ')', '\x12', '+', '\x2', '-', '\x2', '/', 
		'\x13', '\x31', '\x14', '\x33', '\x15', '\x35', '\x16', '\x37', '\x17', 
		'\x39', '\x18', '\x3', '\x2', '\f', '\n', '\x2', '$', '$', '\x31', '\x31', 
		'^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', 
		'\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x5', '\x2', '\x2', '!', 
		'$', '$', '^', '^', '\x3', '\x2', '\x32', ';', '\x4', '\x2', 'G', 'G', 
		'g', 'g', '\x4', '\x2', '-', '-', '/', '/', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', 
		'\x2', '>', '@', '\x2', '\xBA', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '\x3', ';', '\x3', '\x2', '\x2', '\x2', '\x5', '=', '\x3', 
		'\x2', '\x2', '\x2', '\a', '?', '\x3', '\x2', '\x2', '\x2', '\t', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x43', '\x3', '\x2', '\x2', '\x2', 
		'\r', '\x45', '\x3', '\x2', '\x2', '\x2', '\xF', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'I', '\x3', '\x2', '\x2', '\x2', '\x13', 'L', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'O', '\x3', '\x2', '\x2', '\x2', '\x17', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'V', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'[', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x66', '\x3', '\x2', '\x2', '\x2', '!', 'p', '\x3', '\x2', 
		'\x2', '\x2', '#', 'u', '\x3', '\x2', '\x2', '\x2', '%', '{', '\x3', '\x2', 
		'\x2', '\x2', '\'', '}', '\x3', '\x2', '\x2', '\x2', ')', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '+', '\x8F', '\x3', '\x2', '\x2', '\x2', '-', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '/', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\x33', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xA4', '\x3', '\x2', '\x2', '\x2', '\x37', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xB3', '\x3', '\x2', '\x2', '\x2', ';', 
		'<', '\a', '}', '\x2', '\x2', '<', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\a', '.', '\x2', '\x2', '>', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'?', '@', '\a', '\x7F', '\x2', '\x2', '@', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\a', '<', '\x2', '\x2', '\x42', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '\x44', '\a', ']', '\x2', '\x2', '\x44', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x46', '\a', '_', '\x2', '\x2', '\x46', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '\x30', '\x2', '\x2', 
		'H', '\x10', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', ']', '\x2', '\x2', 
		'J', 'K', '\a', ')', '\x2', '\x2', 'K', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\a', ')', '\x2', '\x2', 'M', 'N', '\a', '_', '\x2', '\x2', 
		'N', '\x14', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', ']', '\x2', '\x2', 
		'P', 'Q', '\a', '\x41', '\x2', '\x2', 'Q', 'R', '\a', '*', '\x2', '\x2', 
		'R', '\x16', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '+', '\x2', '\x2', 
		'T', 'U', '\a', '_', '\x2', '\x2', 'U', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'V', 'W', '\a', 'v', '\x2', '\x2', 'W', 'X', '\a', 't', '\x2', '\x2', 
		'X', 'Y', '\a', 'w', '\x2', '\x2', 'Y', 'Z', '\a', 'g', '\x2', '\x2', 
		'Z', '\x1A', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', 'h', '\x2', 
		'\x2', '\\', ']', '\a', '\x63', '\x2', '\x2', ']', '^', '\a', 'n', '\x2', 
		'\x2', '^', '_', '\a', 'u', '\x2', '\x2', '_', '`', '\a', 'g', '\x2', 
		'\x2', '`', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\a', 
		'p', '\x2', '\x2', '\x62', '\x63', '\a', 'w', '\x2', '\x2', '\x63', '\x64', 
		'\a', 'n', '\x2', '\x2', '\x64', '\x65', '\a', 'n', '\x2', '\x2', '\x65', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x66', 'k', '\a', '$', '\x2', '\x2', 
		'g', 'j', '\x5', '!', '\x11', '\x2', 'h', 'j', '\x5', '\'', '\x14', '\x2', 
		'i', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'h', '\x3', '\x2', '\x2', '\x2', 
		'j', 'm', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\x3', '\x2', '\x2', '\x2', 
		'm', 'k', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', '$', '\x2', '\x2', 
		'o', ' ', '\x3', '\x2', '\x2', '\x2', 'p', 's', '\a', '^', '\x2', '\x2', 
		'q', 't', '\t', '\x2', '\x2', '\x2', 'r', 't', '\x5', '#', '\x12', '\x2', 
		's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 'r', '\x3', '\x2', '\x2', '\x2', 
		't', '\"', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', 'w', '\x2', '\x2', 
		'v', 'w', '\x5', '%', '\x13', '\x2', 'w', 'x', '\x5', '%', '\x13', '\x2', 
		'x', 'y', '\x5', '%', '\x13', '\x2', 'y', 'z', '\x5', '%', '\x13', '\x2', 
		'z', '$', '\x3', '\x2', '\x2', '\x2', '{', '|', '\t', '\x3', '\x2', '\x2', 
		'|', '&', '\x3', '\x2', '\x2', '\x2', '}', '~', '\n', '\x4', '\x2', '\x2', 
		'~', '(', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\a', '/', '\x2', 
		'\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x89', '\x5', '+', '\x16', '\x2', '\x83', '\x85', '\a', '\x30', '\x2', 
		'\x2', '\x84', '\x86', '\t', '\x5', '\x2', '\x2', '\x85', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x89', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', '\x5', '-', '\x17', 
		'\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '*', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x90', '\t', '\x5', '\x2', '\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', 
		',', '\x3', '\x2', '\x2', '\x2', '\x93', '\x95', '\t', '\x6', '\x2', '\x2', 
		'\x94', '\x96', '\t', '\a', '\x2', '\x2', '\x95', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x5', '+', '\x16', '\x2', 
		'\x98', '.', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\t', '\b', '\x2', 
		'\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\b', '\x18', '\x2', '\x2', '\x9F', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '&', '\x2', '\x2', '\xA1', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '\x42', '\x2', 
		'\x2', '\xA3', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 
		'%', '\x2', '\x2', '\xA5', '\xA9', '\t', '\t', '\x2', '\x2', '\xA6', '\xA8', 
		'\t', '\n', '\x2', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA8', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xB0', '\t', '\t', '\x2', '\x2', '\xAD', '\xAF', '\t', '\n', 
		'\x2', '\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', 
		'\t', '\v', '\x2', '\x2', '\xB4', ':', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x2', 'i', 'k', 's', '\x80', '\x87', '\x89', '\x8C', '\x91', '\x95', 
		'\x9C', '\xA9', '\xB0', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace JsonLT.Parser
