//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\parser\JsonLT.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace JsonLT.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJsonLTListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class JsonLTBaseListener : IJsonLTListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] JsonLTParser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] JsonLTParser.JsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj([NotNull] JsonLTParser.ObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj([NotNull] JsonLTParser.ObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember([NotNull] JsonLTParser.MemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember([NotNull] JsonLTParser.MemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] JsonLTParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] JsonLTParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElements([NotNull] JsonLTParser.ElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElements([NotNull] JsonLTParser.ElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] JsonLTParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] JsonLTParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] JsonLTParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] JsonLTParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.subpath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubpath([NotNull] JsonLTParser.SubpathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.subpath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubpath([NotNull] JsonLTParser.SubpathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.foreach"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeach([NotNull] JsonLTParser.ForeachContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.foreach"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeach([NotNull] JsonLTParser.ForeachContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] JsonLTParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] JsonLTParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonLTParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresion([NotNull] JsonLTParser.ExpresionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonLTParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresion([NotNull] JsonLTParser.ExpresionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace JsonLT.Parser
